# SPDX-License-Identifier: Multics or MIT-0
# Copyright (c) 2025 Jeffrey H. Johnson
# Copyright (c) 2025 The DPS8M Development Team
# scspell-id: eddef2dc-9923-11f0-ab71-80ee73e9b8e7

version = 1
SPDX-PackageName = "font-gct-multics"
SPDX-PackageSupplier = "Jeffrey H. Johnson <trnsz@pobox.com>"
SPDX-PackageDownloadLocation = "https://gitlab.com/johnsonjh/font-gct"

[[annotations]]
path = "gct_*_"
precedence = "aggregate"
SPDX-FileCopyrightText = ["Copyright (c) 1972 The Massachusetts Institute of Technology", "Copyright (c) 1972-1982 Honeywell Information Systems, Inc.", "Copyright (c) 2006 Bull HN Information Systems, Inc.", "Copyright (c) 2006 Bull SAS"]
SPDX-License-Identifier = "Multics"
